name: nn_counter_tracker_example
description: Example app demonstrating nn_counter_tracker.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  nn_counter_tracker:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
